version: '3.7'
services:
  twitter-to-kafka-service:
    build:
      context: ../twitter-to-kafka-service
      dockerfile: Dockerfile
    ports:
      - "5005:5005"
    volumes:
      - "./docker-logs:/workspace/twitter-to-kafka-service/logs"
      - "./check-config-server-started.sh:/usr/local/bin/check-config-server-started.sh"
    user: root
    command: bash -c "
        check-config-server-started.sh
        && java -jar twitter-to-kafka-service-0.0.1-SNAPSHOT.jar
      "
    environment:
      - "JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -Xms128m -Xmx256m"
      - "LOGGING_LEVEL_COM_MICROSERVICES_DEMO=info"
      - "LOGGING_LEVEL_ROOT=info"
      - "KAFKA-CONFIG_TOPIC-NAME=twitter-topic"
      - "KAFKA-CONFIG_BOOTSTRAP-SERVERS=kafka-broker-1:9092, kafka-broker-2:9092, kafka-broker-3:9092"
      - "KAFKA-CONFIG_SCHEMA-REGISTRY-URL=http://schema-registry:8081"
      - "TWITTER-TO-KAFKA-SERVICE_ENABLE-MOCK-TWEETS=false"
      - "JASYPT_ENCRYPTOR_PASSWORD=${JASYPT_ENCRYPTOR_PASSWORD}"
      - "TWITTER_BEARER_TOKEN=${TWITTER_BEARER_TOKEN}"
      - "SPRING_CLOUD_CONFIG_URI=http://config-server:8888"
    networks:
      - ${GLOBAL_NETWORK:-services}
    depends_on:
      - kafka-broker-1
      - kafka-broker-2
      - kafka-broker-3
      - schema-registry
      - zookeeper
  config-server:
    build:
      context: ../config-server
      dockerfile: Dockerfile
    ports:
      - "5006:5006"
    volumes:
      - "./docker-logs:/workspace/config-server/logs"
    environment:
      - "JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5006 -Xms128m -Xmx256m"
      - "JASYPT_ENCRYPTOR_PASSWORD=${JASYPT_ENCRYPTOR_PASSWORD}"
    networks:
      - ${GLOBAL_NETWORK:-services}
